### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by urbels** [babua/TelegramSteamSaleBot#1]
Hi!

Added bot to group chat, turned it on with start. It shows sales only first time - it doesn`t do it automatically next time.

**Comment by babua** [comment]
Hi, sorry about the late reply, I missed the email notification. There was a time that the bot crashed on the server, could it have been about that? Does the problem still persist? I've been using it both as a personal subscription and in a group, and it seems to be working for me. Is there any more information you can provide to help me try to solve your issue?

**Comment by urbels** [comment]
What was the bot name? @SteamSaleBot? If yes, i`ll try it again.

**Comment by babua** [comment]
Yup, that's the one. Thanks for letting me know about the problem, and I hope it's working for you now!

**Comment by urbels** [comment]
Added it on November 10, it posted deals from that day and for now 2 days nothing.

**Comment by babua** [comment]
Alright, I've received messages on Nov 11 and 12 so the issue is demonstrably there. I'll try to find the source of the bug, but I have no idea why this is happening at the moment, so I can only hope I can find a solution.

**Comment by urbels** [comment]
ok, good luck!

**Comment by urbels** [comment]
looks like it`s working now.

**Comment by babua** [comment]
good to hear, and thanks for letting me know.

**Comment by urbels** [comment]
again not working
